# Generated by Django 4.0.4 on 2022-05-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_authentication_image_alter_registration_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='image',
            field=models.ImageField(upload_to='dataset_engage/test_images'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='image',
            field=models.ImageField(upload_to='dataset_engage/test_images'),
        ),
        migrations.AlterField(
            model_name='registration_teacher',
            name='image',
            field=models.ImageField(upload_to='dataset_engage/test_images'),
        ),
    ]
